config/routes.rb
Yaswanth::Application.routes.draw do

  resources :blog_entries

  resources :categories

  resources :blogs

   root :to => 'blogs#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :description, :name
end

app/models/blog_entry.rb
class BlogEntry < ActiveRecord::Base
  attr_accessible :content, :published, :title, :category_ids

  scope :yash, -> { where("content IS NOT NULL") }

  has_many :blog_entry_categories
  has_many :categories, :through => :blog_entry_categories
 
  validates :blog_entry_categories, :presence => {:message => 'sumit'}

end

app/models/blog_entry_category.rb
class BlogEntryCategory < ActiveRecord::Base
  attr_accessible :blog_entry_id, :category_id

  belongs_to :blog_entry
  belongs_to :category
end

app/models/blog_entry_observer.rb
class BlogEntryObserver < ActiveRecord::Observer
  def after_create(blog_entry)
  	puts "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  	blog_entry.logger.info('New contact added!')
 	UserMailer.registration_confirmation(nil).deliver
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name

  has_many :blog_entry_categories
  has_many :blog_entries, :through => :blog_entry_categories

end

app/models/notification_observer.rb
class NotificationObserver < ActiveRecord::Observer
	observe :blog_entry

  def before_save
  	puts "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
 	UserMailer.registration_confirmation(nil).deliver
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blog_entries_controller.rb
class BlogEntriesController < ApplicationController
  def index
    @blog_entries = BlogEntry.yash
  end

  def show
    @blog_entry = BlogEntry.find(params[:id])
  end

  def new
    @blog_entry = BlogEntry.new
    @categories = Category.all
  end

  def create
    @blog_entry = BlogEntry.new(params[:blog_entry])

    if params['category_ids'].present?
        params['category_ids'].each do |category_id|
        @blog_entry_category = @blog_entry.blog_entry_categories.build(:category_id => category_id)
        @blog_entry_category.save
      end 
    end

    respond_to do |format|
      if @blog_entry.save
        format.html { redirect_to @blog_entry, notice: 'Blog Entry was successfully updated.' }
        format.json { render json: @blog_entry, status: :created, location: @blog_entry }
      else
        format.html { render action: "new" }
        format.json { render json: @blog_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @blog_entry = BlogEntry.find(params[:id])
    @blog_entry.destroy

    respond_to do |format|
      format.html { redirect_to blog_entries_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

	def index
		@blogs = Blog.all
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index
  	@categories = Category.all
  end

  def new
	@category = Category.new
  end

  def create
	@category = Category.new(params[:category])
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end

  end

	def show
		@category = Category.find(params[:id])
	end

	def edit
		
	end

	def update
		
	end

	def delete
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_entries_helper.rb
module BlogEntriesHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/blog_entries/create.html.erb
<h1>BlogEntries#create</h1>
<p>Find me in app/views/blog_entries/create.html.erb</p>

app/views/blog_entries/delete.html.erb
<h1>BlogEntries#delete</h1>
<p>Find me in app/views/blog_entries/delete.html.erb</p>

app/views/blog_entries/edit.html.erb
<h1>BlogEntries#edit</h1>
<p>Find me in app/views/blog_entries/edit.html.erb</p>

app/views/blog_entries/index.html.erb
<h1>Listing Blog Entries</h1>

<%= link_to("New Blog Entry", new_blog_entry_path) %>
<%= link_to("New Category", new_category_path) %>
<table>
	<thead>
		<th>Title</th>
		<th>Content</th>
		<th>Published</th>
		<th></th>
		<th></th>
	</thead>
	<tbody>
		<% @blog_entries.each do |blog_entry| %>
		<tr>
			<td><%=blog_entry.title%></td>
			<td><%=blog_entry.content%></td>
			<td><%=blog_entry.published%></td>
			<td><%=link_to 'Show', blog_entry, id: 'show_id' %></td>
			<td><%=link_to 'Destroy', blog_entry,id: 'show_id', method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/blog_entries/new.html.erb
<h1>BlogEntries</h1>
<%= form_for(@blog_entry) do |f| %>

  <% if @blog_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_entry.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @blog_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


	<div>
		<%= f.label 'Blog Title' %>
		<%= f.text_field :title%>
	</div>
	<div>
		<%= f.label 'Content' %>
		<%= f.text_field :content%>
	</div>
	<div>
		<%= f.label 'published' %>
		<%= f.date_select :published%>
	</div>
<div>
  <label>Categories:</label>
	<%= select_tag 'category_ids', options_from_collection_for_select(Category.all, "id", "name"), { :multiple => true} %>
</div>



	<%= f.submit%>
<%end%>

app/views/blog_entries/show.html.erb
<h1>Blog Entry</h1>
<div style="height: 40px">
	<label>Title:</label><span><%= @blog_entry.title %></span>
</div>
<div style="height: 40px">
	<label>Content:</label><span><%= @blog_entry.content %></span>
</div>
<div style="height: 40px">
	<label>Published:</label><span><%= @blog_entry.published %></span>
</div>
<label>Category:</label>
<% @blog_entry.categories.each do |category| %>
	<span class="sumit"><%= category.name %></span>
<% end %>

app/views/blog_entries/update.html.erb
<h1>BlogEntries#update</h1>
<p>Find me in app/views/blog_entries/update.html.erb</p>

app/views/blogs/index.html.erb
<style>
body{

	background-image: url('http://edudemic.com/wp-content/uploads/2012/08/blog.jpg');
}
</style>

<div>
	<%= link_to 'Category', categories_path %>
</div>
<div>
	<%= link_to 'Blog Entry', blog_entries_path %>
</div>

app/views/categories/index.html.erb
<h1>Listing Categories</h1>

<%= link_to("New Category", new_category_path) %> |
<%= link_to("New Blog Entry", new_blog_entry_path) %>
<table class="my_table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Description</th>	
		</tr>
	</thead>
	<tbody>
		<% for @cat in @categories %>
		<tr>
			<td><%= @cat.name %></td>
			<td><%= @cat.description %></td>
			<td><%= link_to 'Show', @cat %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/categories/new.html.erb
<h1>New Category</h1>
<%= form_for(@category) do |f| %>
	<%= f.label 'Category Name' %>
	<%= f.text_field :name%>
	<%= f.label 'Category Description' %>
	<%= f.text_field :description%>
	<%= f.submit%>
<%end%>

app/views/categories/show.html.erb
<style>
body{

	background-image: url('http://hdwallpaperswala.com/wp-content/uploads/2014/01/lok_sabha_india_hd_images_computer_background.jpg');
}
</style>
<h1>Category</h1>
<div style="height: 40px">
	<label>Name:</label><span><%= @category.name%></span>
</div>
<div style="height: 40px">
	<label>Description:</label><span><%= @category.description%></span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yaswanth</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>